version: '3.8'

services:
  backend:
    build: ./backend
    container_name: school-bus-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/school_bus_db
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: school-bus-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongo:
    image: mongo:7.0
    container_name: school-bus-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=school_bus_db
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
